default:
    cargo build --bin search_memory --release
    time cargo run --bin search_memory --release 

run BIN:
    cargo build --bin {{BIN}} --release
    time cargo run --bin {{BIN}} --release 

test:
    cargo test
